echo -e "\033[1;34m"
echo -e "\033[1;36m"
echo
echo -e "PPPPPPPPPPPPPPPPP                                        MMMMMMMM               MMMMMMMM  iiii                            tttt           "
echo -e "P::::::::::::::::P                                       M:::::::M             M:::::::M i::::i                        ttt:::t           "
echo -e "P::::::PPPPPP:::::P                                      M::::::::M           M::::::::M  iiii                         t:::::t           "
echo -e "PP:::::P     P:::::P                                     M:::::::::M         M:::::::::M                               t:::::t           "
echo -e " P::::P     P:::::Prrrrr   rrrrrrrrr      ooooooooooo   M::::::::::M       M::::::::::Miiiiiiinnnn  nnnnnnnn    ttttttt:::::ttttttt      "
echo -e " P::::P     P:::::Prrrrr   rrrrrrrrr      ooooooooooo   M::::::::::M       M::::::::::Miiiiiiinnnn  nnnnnnnn    ttttttt:::::ttttttt      "
echo -e " P::::P     P:::::Prrrrr   rrrrrrrrr      ooooooooooo   M::::::::::M       M::::::::::Miiiiiiinnnn  nnnnnnnn    ttttttt:::::ttttttt      "
echo -e "  P::::P     P:::::Prrrrr   rrrrrrrrr      ooooooooooo   M::::::::::M       M::::::::::Miiiiiiinnnn  nnnnnnnn    ttttttt:::::ttttttt     "
echo -e "  P::::P     P:::::Pr::::rrr:::::::::r   oo:::::::::::oo M:::::::::::M     M:::::::::::Mi:::::in:::nn::::::::nn  t:::::::::::::::::t     "
echo -e "  P::::PPPPPP:::::P r:::::::::::::::::r o:::::::::::::::oM:::::::M::::M   M::::M:::::::M i::::in::::::::::::::nn t:::::::::::::::::t     "
echo -e "  P:::::::::::::PP  rr::::::rrrrr::::::ro:::::ooooo:::::oM::::::M M::::M M::::M M::::::M i::::inn:::::::::::::::ntttttt:::::::tttttt     "
echo -e "  P::::PPPPPPPPP     r:::::r     r:::::ro::::o     o::::oM::::::M  M::::M::::M  M::::::M i::::i  n:::::nnnn:::::n      t:::::t           "
echo -e "  P::::P             r:::::r     rrrrrrro::::o     o::::oM::::::M   M:::::::M   M::::::M i::::i  n::::n    n::::n      t:::::t           "
echo -e "  P::::P             r:::::r            o::::o     o::::oM::::::M    M:::::M    M::::::M i::::i  n::::n    n::::n      t:::::t           " 
echo -e "  P::::P             r:::::r            o::::o     o::::oM::::::M     MMMMM     M::::::M i::::i  n::::n    n::::n      t:::::t    tttttt "
echo -e "PP::::::PP           r:::::r            o:::::ooooo:::::oM::::::M               M::::::Mi::::::i n::::n    n::::n      t::::::tttt:::::t "
echo -e "P::::::::P           r:::::r            o:::::::::::::::oM::::::M               M::::::Mi::::::i n::::n    n::::n      tt::::::::::::::t "
echo -e "P::::::::P           r:::::r             oo:::::::::::oo M::::::M               M::::::Mi::::::i n::::n    n::::n        tt:::::::::::tt " 
echo -e "PPPPPPPPPP           rrrrrrr               ooooooooooo   MMMMMMMM               MMMMMMMMiiiiiiii nnnnnn    nnnnnn          ttttttttttt   "
echo
echo -e "\032[1;33mTelegram channel: \033[5;31mhttps://t.me/ProMintChannel\033[0m"
echo -e "\033[0m"
