echo -e "\033[1;34m"
echo -e "\033[1;36m"
echo
echo -e "PPPPPPPPPPPPPPPPP                                           MMMMMMMM               MMMMMMMM   iiii                              tttt          "
echo -e "P::::::::::::::::P                                          M:::::::M             M:::::::M  i::::i                           ttt:::t         "
echo -e "P::::::PPPPPP:::::P                                         M::::::::M           M::::::::M   iiii                            t:::::t         "
echo -e "PP:::::P     P:::::P                                        M:::::::::M         M:::::::::M                                   t:::::t         "
echo -e "  P::::P     P:::::P rrrrr   rrrrrrrrr       ooooooooooo    M::::::::::M       M::::::::::M iiiiiii nnnn  nnnnnnnn     ttttttt:::::ttttttt    "
echo -e "  P::::P     P:::::P r::::rrr:::::::::r    oo:::::::::::oo  M:::::::::::M     M:::::::::::M i:::::i n:::nn::::::::nn   t:::::::::::::::::t    "
echo -e "  P::::PPPPPP:::::P  r:::::::::::::::::r  o:::::::::::::::o M:::::::M::::M   M::::M:::::::M  i::::i n::::::::::::::nn  t:::::::::::::::::t    "
echo -e "  P:::::::::::::PP   rr::::::rrrrr::::::r o:::::ooooo:::::o M::::::M M::::M M::::M M::::::M  i::::i nn:::::::::::::::n tttttt:::::::tttttt    "
echo -e "  P::::PPPPPPPPP      r:::::r     r:::::r o::::o     o::::o M::::::M  M::::M::::M  M::::::M  i::::i   n:::::nnnn:::::n       t:::::t          "
echo -e "  P::::P              r:::::r     rrrrrrr o::::o     o::::o M::::::M   M:::::::M   M::::::M  i::::i   n::::n    n::::n       t:::::t          "
echo -e "  P::::P              r:::::r             o::::o     o::::o M::::::M    M:::::M    M::::::M  i::::i   n::::n    n::::n       t:::::t          "
echo -e "  P::::P              r:::::r             o::::o     o::::o M::::::M     MMMMM     M::::::M  i::::i   n::::n    n::::n       t:::::t    tttttt"
echo -e "PP::::::PP            r:::::r             o:::::ooooo:::::o M::::::M               M::::::M i::::::i  n::::n    n::::n       t::::::tttt:::::t"
echo -e "P::::::::P            r:::::r             o:::::::::::::::o M::::::M               M::::::M i::::::i  n::::n    n::::n       tt::::::::::::::t"
echo -e "P::::::::P            r:::::r              oo:::::::::::oo  M::::::M               M::::::M i::::::i  n::::n    n::::n         tt:::::::::::tt"
echo -e "PPPPPPPPPP            rrrrrrr                ooooooooooo    MMMMMMMM               MMMMMMMM iiiiiiii  nnnnnn    nnnnnn           ttttttttttt  "
echo
echo -e "\032[1;33mTelegram channel: \033[5;31mhttps://t.me/ProMintChannel\033[0m"
echo -e "\033[0m"
